src/services/items/fluent-schema.ts
=> refactor: allow additional properties for settings

README.md
This PR updates the faulty link in README.
closes #164
=> fix: change item login link to point to the right file

src/services/items/service-api.ts, src/util/config.ts, yarn.lock
Add the options for validation plugin
=> fix: add plugin options

package.json, src/services/items/service-api.ts, yarn.lock
This PR scopes the core routes with the action hook declaration so that they do not interfere.
closes #177
=> fix: scope onResponse with core routes

src/services/item-memberships/tasks/get-member-item-membership-over-item-task.ts, test/membership.test.ts, yarn.lock
This PR fixes the error returned when validating a member's permission over an item.
closes #186
=> fix: error on get member item membership over item

README.md, package.json, yarn.lock
=> docs: update readme with invitations db schema

package.json, src/plugins/auth/auth.ts, src/util/config.ts, yarn.lock
=> refactor: update redirect link

README.md, package.json, src/plugins/auth/auth.ts, src/services/items/fluent-schema.ts, src/services/items/handler/item-action-handler.ts, src/services/items/interfaces/item-task-manager.ts, src/services/items/service-api.ts, src/services/items/task-manager.ts, src/services/items/tasks/get-item-descendants-task.ts, test/fixtures/items.ts, test/fixtures/members.ts, test/fixtures/utils.ts, test/item.test.ts, test/mocks.ts, test/utils.ts, yarn.lock
close #220
renamed branch of #221
=> 220 descendants

README.md, src/util/config.ts
=> fix: add h5p env vars in README

README.md, package.json, yarn.lock
This PR updates the version of the chatbox plugin used to include chat mentions.
Readme was updated.
⚠️ **Migration Needed** ⚠️
A Migration is needed for the mentions to work.
See: [https://github.com/graasp/graasp-plugin-chatbox/blob/main/migrations/migration2.sql](https://github.com/graasp/graasp-plugin-chatbox/blob/main/migrations/migration2.sql)
⚠️
closes #237
=> feat: add mentions to chat

src/plugins/database.ts, src/services/item-memberships/tasks/delete-item-item-memberships-task.ts, src/services/items/base-item.ts, src/services/items/constants/constants.ts, src/services/items/fluent-schema.ts, src/services/items/schemas.ts, src/services/items/service-api.ts, src/services/items/task-manager.ts, src/services/items/tasks/copy-item-task.ts, src/services/items/tasks/create-item-task.ts, src/services/items/tasks/delete-item-task.ts, src/services/items/tasks/get-item-descendants-task.ts, src/services/items/tasks/move-item-task.ts, src/services/members/schemas.ts, src/util/config.ts, test/fixtures/items.ts, test/item.test.ts, test/membership.test.ts, yarn.lock
=> refactor: increase idle timeout

src/services/items/tasks/delete-item-task.ts, yarn.lock
=> refactor: update yarn lock

package.json, yarn.lock
=> fix: upgrade h5p plugin with upload task runner bypass

src/util/config.ts, yarn.lock
=> refactor: update graasp-sdk, use Context.library

.github/workflows/cdelivery-ecs-backend-caller.yml, .github/workflows/cdeployment-ecs-backend-caller.yml, .github/workflows/cintegration-ecs-backend-caller.yml, README.md, src/app.ts, src/plugins/database.ts, src/util/config.ts
=> feat: implement DB read replicas

src/plugins/database.ts, test/plugins/database.test.ts
Closes #286 and fixes https://github.com/graasp/graasp/actions/runs/3787978449
=> fix: correctly assign interceptors when undefined

src/util/config.ts, yarn.lock
This PR removes superfluous DB calls and connections by ensuring that transactions do not establish additional connections
- Reset the pool size to a sane default
- Update dependencies which erroneously bloat transactions
Related:
- https://github.com/graasp/graasp-apps/pull/67
- https://github.com/graasp/graasp-plugin-chatbox/pull/47
- https://github.com/graasp/graasp-plugin-file-item/pull/39
- https://github.com/graasp/graasp-plugin-h5p/pull/11
- https://github.com/graasp/graasp-plugin-hidden-items/pull/8
- https://github.com/graasp/graasp-plugin-recycle-bin/pull/41
- https://github.com/graasp/graasp-plugin-thumbnails/pull/28
- https://github.com/graasp/graasp-plugin-invitations/pull/7
Closes #287
=> Isolate transactions

.github/workflows/cdelivery-ecs-backend-caller.yml, .github/workflows/cdeployment-ecs-backend-caller.yml, .github/workflows/cintegration-ecs-backend-caller.yml, package.json, src/services/global-task-runner.ts, src/util/config.ts, yarn.lock
Re-apply changes from #291 with deps updates
=> fix: isolate transactions

package.json, yarn.lock
Update yarn lock with the new fix in recycle bin + some packages to resolve security issues
=> Update recycle bin dependency + security issues

.github/workflows/cdelivery-ecs-backend-caller.yml, .github/workflows/cdeployment-ecs-backend-caller.yml, .github/workflows/cintegration-ecs-backend-caller.yml, .github/workflows/nodejs.yml
=> ci: abort previously running jobs if newer version is running

package.json, yarn.lock
Update validation plugin with its fix.
=> fix: update validation plugin

package.json, yarn.lock
This PR updates the invitation branch (that includes the permission fix)
=> fix: update invitation permission

package.json, yarn.lock
Fix content-disposition header invalid error.
=> refactor: update zip package

.devcontainer/.env, .devcontainer/docker-compose.yml, README.md, yarn.lock
=> chore: remove external access to redis container

.devcontainer/db/Dockerfile
Databases will be slowly updated to 15.2, currently only the one on Dev environement is done.
We match the local database version to the expected deployment version for consistency
=> chore: update postgres container to 15

src/services/item/plugins/app/publisherRepository.ts, src/services/item/plugins/published/index.ts, src/services/item/plugins/published/repositories/itemPublished.ts, src/services/item/plugins/published/schemas.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts
=> refactor: add get recent collections endpoint

src/services/item/repository.ts, src/services/item/service.ts, src/services/item/test/index.test.ts
=> fix: create membership for copied item

.github/workflows/cdelivery-ecs-backend-caller.yml, .github/workflows/cdeployment-ecs-backend-caller.yml, .github/workflows/deploy-development.yml
This PR updates the deployment workflows
ref https://github.com/graasp/graasp-deploy/pull/201
=> fix: update deployment workflows

src/plugins/datasource.ts
This PR disable some logging to avoid flooding the console.
=> refactor: clean typeorm logging

src/declarations.d.ts, src/server.ts, src/services/action/utils/export.test.ts, src/services/action/utils/export.ts, src/services/chat/index.ts, src/services/chat/repository.ts, src/services/chat/test/chatMessage.test.ts, src/services/item/index.ts, src/services/item/plugins/action/base-analytics.test.ts, src/services/item/plugins/action/base-analytics.ts, src/services/item/plugins/action/index.ts, src/services/item/plugins/action/requestExport/repository.ts, src/services/item/plugins/action/requestExport/service.ts, src/services/item/plugins/action/service.ts, src/services/item/plugins/action/test/index.test.ts, src/services/member/test/fixtures/members.ts, yarn.lock
This PR adds chat messages to export-actions, since the feature disappeared from the chat plugin. 
close #458
=> feat: export chat messages

.prettierignore, docker/Dockerfile
fixes #389 
Don't forget to also merge https://github.com/graasp/graasp-deploy/pull/202
=> chore: rename .stagingcontainer to docker for clarity

package.json, src/migrations/1689666251815-clean-tags.ts, test/migrations/migrations1683637099103/fixture.ts, test/migrations/migrations1689666251815/fixture.ts, test/migrations/migrations1689666251815/migrations.test.ts
=> fix: add migration to clean tags

.devcontainer/Dockerfile
Loads git bash completions for the node user in the devcontainer
=> chore: load git bash completions in devcontainer

.github/workflows/test.yml, src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/invitation/constants.ts, src/utils/config.ts
=> feat: replace mobile redirect with domain-based deep link

package.json, src/services/action/repositories/action.ts, src/services/action/services/action.ts, src/services/action/utils/actions.ts, src/services/action/utils/errors.ts, src/services/item/plugins/action/index.ts, src/services/item/plugins/action/schemas.ts, src/services/item/plugins/action/service.ts, src/services/item/plugins/action/test/fixtures/actions.ts, src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/action/utils.ts, yarn.lock
Aggregate endpoint 
rebased and squashed branch 
close #412 
---------
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Kim Lan Phan Hoang <pyphilia@gmail.com>
Co-authored-by: kim <kim.phanhoang@epfl.ch>
feat: prevent saving actions if disabled
fix: fix aggregation
fix: address comments
fix: fix actions test
fix: address comments
=> feat: add aggregate action endpoint

.dockerignore
=> chore: add docs folder to dockerignore

src/services/auth/index.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/mobile/schemas.ts, src/utils/config.ts
=> feat: always redirect mobile auth to universal auth link

src/migrations/1692624998160-category-seed.ts, test/migrations/migrations1692624998160/migrations.test.ts
=> feat: add italian and arabic categories, refactor categories name

src/services/item/plugins/app/appData/plugins/file/index.ts, src/services/item/plugins/app/appData/repository.ts, src/services/item/plugins/app/appData/test/index.test.ts
This PR enabled back a commented test. It also fixes some other tests.
close #506
=> test: fix Patch app data file test

src/app.ts, src/declarations.d.ts, src/services/action/index.ts, src/services/item/plugins/action/index.ts, src/services/item/plugins/h5p/index.ts, src/services/item/plugins/h5p/types.ts, src/services/itemMembership/index.ts, src/services/member/plugins/action/index.ts
=> fix: use mailer in itemMembership service, fix notification

src/services/chat/plugins/mentions/service.ts, src/services/itemMembership/service.ts, src/services/itemMembership/test/index.test.ts, src/services/utils.ts
=> fix: remove im's create function, notify on post

src/services/action/utils/actions.test.ts, src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/schemas.ts, src/services/auth/plugins/password/index.ts, src/services/auth/plugins/password/schemas.ts, src/services/auth/service.ts, src/services/auth/utils.ts, src/services/chat/plugins/mentions/service.ts, src/services/invitation/constants.ts, src/services/invitation/service.ts, src/services/invitation/test/index.test.ts, src/services/item/plugins/action/test/index.test.ts, src/services/itemMembership/service.ts, src/services/utils.ts, src/utils/config.ts
=> feat: handle redirection url in auth endpoints

package.json, src/declarations.d.ts, src/plugins/decorator.ts, src/services/item/plugins/action/requestExport/service.ts, src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/file/index.ts, src/services/item/plugins/file/service.ts, src/services/item/repository.ts, src/services/member/controller.ts, src/services/member/plugins/storage/service.ts, src/services/member/schemas.ts, src/services/member/test/index.test.ts, yarn.lock
Created a `StorageService` to contain functions related to storage.
Kept in mind the maximum storage can be different for each user.
close #575
=> feat: implement get current member storage

src/migrations/1695655073720-gist-action-path.ts, src/plugins/database.ts, src/sentry.ts, src/services/action/entities/action.ts, src/services/action/repositories/action.ts, src/utils/errors.ts, test/migrations/migrations1679669193721/migrations.test.ts, test/migrations/migrations1679669193721/migrations1679669193721.fixtures.ts, test/migrations/migrations1683637099103/migrations.test.ts, test/migrations/migrations1689666251815/migrations.test.ts
Add indices on action entity.
+ some mini fixes to solve lint errors.
close #622
=> feat: add indices on action entity

README.md
=> docs: update readme instructions for localstack

src/services/item/plugins/app/appData/repository.ts, src/services/item/plugins/app/appData/schemas.ts, src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appData/test/index.test.ts
Text input cannot set the member because the backend doesn't. 
This should fix the error, I've added a corresponding test.
close #661
=> fix: set member id on post app data

src/sentry.ts
In this PR I add an option to filter events we send to sentry.
=> fix: filter sentry events at the source

package.json, src/services/item/plugins/app/entities/app.ts, src/services/item/plugins/app/entities/publisher.ts, src/services/item/plugins/etherpad/test/service-api.test.ts, src/services/item/plugins/html/h5p/index.ts, src/services/item/plugins/html/h5p/service.ts, src/services/item/plugins/published/plugins/search/meilisearch.ts, src/services/item/plugins/published/test/index.test.ts, src/services/item/service.ts, src/services/item/test/index.test.ts, src/services/item/ws/events.ts, yarn.lock
- fix: mismatched types from sdk update
- fix: use optional on folder extra that might be empty fix #679
=> fix: update to sdk 2.0.0

src/services/item/plugins/shortLink/README.md, src/services/item/plugins/shortLink/entities/ShortLink.ts, src/services/item/plugins/shortLink/index.ts, src/services/item/plugins/shortLink/repository.ts, src/services/item/plugins/shortLink/schemas.ts, src/services/item/plugins/shortLink/service.ts, src/services/item/plugins/shortLink/test/fixtures.ts, src/services/item/plugins/shortLink/test/index.test.ts
see #716 for more information about this PR.
=> feat: implement the get short link route

src/services/item/test/index.test.ts, src/services/itemMembership/repository.ts
=> fix: return shared child in accessible items

.github/workflows/deploy-prod.yml, src/services/item/plugins/importExport/index.ts, src/services/item/plugins/importExport/service.ts
=> fix: add transaction in import post

src/services/item/controller.ts, src/services/item/fluent-schema.ts, src/services/item/test/index.test.ts, src/services/item/types.ts, src/services/itemMembership/repository.ts
=> feat: filter accessible items by permission

src/services/action/utils/export.test.ts, src/services/action/utils/export.ts, src/services/item/plugins/action/base-analytics.test.ts, src/services/item/plugins/action/base-analytics.ts, src/services/item/plugins/action/schemas.ts, src/services/item/plugins/action/service.ts, src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/app/appAction/test/index.test.ts, src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/app/appSetting/test/index.test.ts
=> feat: include app data, setting and actions in analytics

src/services/invitation/repository.ts, src/services/invitation/service.ts, src/services/invitation/test/index.test.ts
=> fix: normalise invitation email

src/services/item/plugins/itemFavorite/repositories/favorite.test.ts, src/services/item/plugins/itemFavorite/repositories/favorite.ts, src/services/item/plugins/itemFavorite/test/index.test.ts
=> fix: return creator for item in favorite

package.json, src/migrations/1705936454722-item-geolocation.ts, src/migrations/1706089724916-item-geolocation.ts, src/plugins/__mocks__/datasource.ts, src/plugins/datasource.ts, src/services/item/controller.ts, src/services/item/entities/Item.ts, src/services/item/fluent-schema.ts, src/services/item/index.ts, src/services/item/plugins/geolocation/ItemGeolocation.ts, src/services/item/plugins/geolocation/errors.ts, src/services/item/plugins/geolocation/index.test.ts, src/services/item/plugins/geolocation/index.ts, src/services/item/plugins/geolocation/repository.test.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/plugins/geolocation/schemas.ts, src/services/item/plugins/geolocation/service.test.ts, src/services/item/plugins/geolocation/service.ts, src/services/item/plugins/geolocation/specifications.md, src/services/item/service.ts, src/services/item/test/fixtures/items.ts, src/services/item/test/index.test.ts, src/utils/repositories.ts, yarn.lock
In the end I've added already lots of endpoints, while thinking of the implementation. 
close #775
=> feat: add geolocation endpoints

src/services/action/utils/export.test.ts, src/services/item/plugins/geolocation/repository.test.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/plugins/published/service.ts, src/services/item/test/fixtures/items.ts, src/services/item/test/index.test.ts, src/services/itemMembership/test/fixtures/memberships.ts
=> fix: filter out recycled items on get geolocation

package.json, src/migrations/1707735413855-geolocation-address.ts, src/plugins/mailer/index.ts, src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/service.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/service.ts, src/services/item/plugins/geolocation/ItemGeolocation.ts, src/services/item/plugins/geolocation/errors.ts, src/services/item/plugins/geolocation/index.test.ts, src/services/item/plugins/geolocation/index.ts, src/services/item/plugins/geolocation/repository.test.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/plugins/geolocation/schemas.ts, src/services/item/plugins/geolocation/service.test.ts, src/services/item/plugins/geolocation/service.ts, src/services/item/plugins/published/service.ts, src/services/member/entities/member.ts, src/services/member/service.ts, src/services/member/test/fixtures/members.ts, yarn.lock
=> feat: get geolocation within item

.devcontainer/docker-compose.yml
=> fix: change smtp config to string

src/services/itemLogin/repositories/itemLogin.ts, src/services/itemLogin/test/index.test.ts
=> fix: reuse item login from parent

src/services/item/plugins/published/plugins/search/meilisearch.ts, src/services/item/repository.ts, src/services/item/service.ts, src/services/item/test/ws.test.ts, src/services/item/utils.test.ts, src/services/item/utils.ts, src/services/websockets/test/multi-instance.test.ts
=> fix: order descendants by default

package.json, src/services/item/fluent-schema.ts, src/services/item/repository.ts, src/services/item/test/index.test.ts, yarn.lock
This PR refer to graasp/graasp-ui#694.
=> feat: add descriptionPlacement support in item settings

src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/app/docs/api.md, src/services/item/test/index.test.ts
=> feat: allow members with read access to post app data for another member

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml, .github/workflows/test.yml, README.md, src/services/item/plugins/geolocation/errors.ts, src/services/item/plugins/geolocation/index.test.ts, src/services/item/plugins/geolocation/index.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/plugins/geolocation/schemas.ts, src/services/item/plugins/geolocation/service.test.ts, src/services/item/plugins/geolocation/service.ts, src/services/item/plugins/geolocation/specifications.md, src/utils/config.ts
=> feat: add geocoding endpoints

.github/workflows/test.yml
In this PR:
- update set-output syntax in test workflow
=> fix: update syntax for set-output in test workflow

src/plugins/datasource.ts
=> feat: increase pool size

src/schemas/global.ts, src/schemas/globals.test.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/magicLink/schemas.ts, src/services/member/schemas.ts, src/services/member/test/index.test.ts
In this PR I apply the new username limits defined in SDK.
=> fix: apply user name limits

src/schemas/global.ts, src/schemas/globals.test.ts, src/services/item/fluent-schema.ts
- This allow spaces only if there is a character after
The Regex I used last weeks allows having multiple space and to end with a space. I changed the regex to not allow that.
=> fix: use () instead of [] in spaces regex

src/services/item/fluent-schema.ts, src/services/item/plugins/file/test/index.test.ts
=> fix: include maxwidth in settings schema

src/services/item/plugins/app/fluent-schema.ts, src/services/item/plugins/app/index.ts, src/services/item/plugins/app/repository.ts, src/services/item/plugins/app/service.ts, src/services/item/plugins/app/test/index.test.ts, yarn.lock
In this PR:
an endpoint is added to get the most used apps from the user
fix #988
=> feat: add endpoint for most-used apps per user

src/services/authorization.test.ts, src/services/authorization.ts, src/services/item/plugins/geolocation/index.test.ts, src/services/item/plugins/geolocation/service.ts, src/services/item/plugins/itemTag/repository.ts, src/services/item/service.ts, src/services/item/test/index.test.ts, src/services/member/repository.ts
=> fix: check that array is empty before getting many tags

src/services/item/plugins/published/service.ts, src/services/item/plugins/validation/index.ts, src/services/item/plugins/validation/service.ts, src/services/item/plugins/validation/test/index.test.ts
Publish the item after the validation if it is valid.
If the item is private, it will be set to public after the validation succeeded (the frontend has to ask to the user).
=> feat: publish automatically when item is validated

src/services/authorization.ts, src/services/item/controller.test.ts, src/services/item/controller.ts, src/services/item/fluent-schema.ts, src/services/item/plugins/action/service.ts, src/services/item/repository.ts, src/services/item/service.ts
=> feat: filters item type and hidden item

src/services/item/ItemWrapper.ts, src/services/item/fluent-schema.ts, src/services/item/plugins/itemTag/errors.ts, src/services/item/plugins/itemTag/repository.ts, src/services/item/plugins/itemTag/schemas.ts, src/services/item/plugins/itemTag/service.test.ts, src/services/item/plugins/itemTag/service.ts, src/services/item/plugins/itemTag/test/index.test.ts
There were instances where we fetch data when the items array is empty.
fix #1107
=> fix: many tags items length

package.json, src/services/item/plugins/published/errors.ts, src/services/item/plugins/published/index.ts, src/services/item/plugins/published/plugins/search/meilisearch.ts, src/services/item/plugins/published/plugins/search/service.ts, src/services/item/plugins/published/repositories/itemPublished.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts, src/services/item/plugins/validation/index.ts, yarn.lock
- feat: restrict publication items to folder
- fix: try to publish only if not already published
- feat: getForItem of publish repository doesn't throw anymore
- chore(dep): update SDK to 4.13.0
=> feat: restrict publication items to folder only

src/services/auth/plugins/passport/constants.ts, src/services/member/schemas.ts, src/services/member/service.ts
=> fix: add email in link for email update

src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/service.ts
- use authService instead of fastify instance in mobile service
- inject mobile service using DI
=> feat(refactor): update MobileService to allow injection using DI

src/@types/declarations.d.ts, src/services/auth/index.ts, src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/service.ts
- use authService instead of fastify instance in the service
- inject the service using DI
=> feat(refactor): update magiclink service to allow injection using DI

src/services/item/controller.ts, src/services/item/fluent-schema.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/repository.test.ts, src/services/item/repository.ts, src/services/item/service.ts, src/services/item/specifications.md, src/services/item/test/index.test.ts, src/services/item/types.ts, src/services/itemMembership/repository.ts
Given keywords, search in many fields thanks to `search_document`.
=> feat: improve search for accessible and children

src/migrations/1723018735439-membership-request.ts, src/plugins/datasource.ts, src/services/itemMembership/index.ts, src/services/itemMembership/plugins/MembershipRequest/entities/MembershipRequest.ts, src/services/itemMembership/plugins/MembershipRequest/index.ts, src/services/itemMembership/plugins/MembershipRequest/repository.ts, src/services/itemMembership/plugins/MembershipRequest/schemas.ts, src/services/itemMembership/plugins/MembershipRequest/service.ts, src/utils/repositories.ts
This pull request is a part of the main issue https://github.com/graasp/graasp/issues/1220.
I've divided it, to make it easier to review and having continuous feedback
The goal of this PR is only to create the corresponding Entity and the structure of the feature. This PR should have no impact on the application.
=> feat(membership request): create entity

src/services/itemMembership/plugins/MembershipRequest/index.test.ts, src/services/itemMembership/plugins/MembershipRequest/index.ts, src/services/itemMembership/plugins/MembershipRequest/repository.ts, src/services/itemMembership/plugins/MembershipRequest/schemas.ts, src/services/itemMembership/plugins/MembershipRequest/service.ts
subfix from https://github.com/graasp/graasp/issues/1220
=> feat(membership request): get all requests from an item

src/services/itemMembership/plugins/MembershipRequest/error.ts, src/services/itemMembership/plugins/MembershipRequest/index.test.ts, src/services/itemMembership/plugins/MembershipRequest/index.ts, src/services/itemMembership/plugins/MembershipRequest/repository.ts, src/services/itemMembership/plugins/MembershipRequest/schemas.ts, src/services/itemMembership/plugins/MembershipRequest/service.ts
=> feat(membership request): delete request route

package.json, src/services/itemMembership/plugins/MembershipRequest/index.test.ts, src/services/itemMembership/plugins/MembershipRequest/index.ts, src/services/itemMembership/plugins/MembershipRequest/schemas.ts, src/services/itemMembership/repository.ts, src/services/itemMembership/schemas.ts, src/services/itemMembership/service.ts, src/services/itemMembership/test/index.test.ts, yarn.lock
=> feat(membership request): get status of you own request

src/repositories/interfaces.ts, src/services/item/plugins/itemCategory/repositories/category.ts, src/services/item/plugins/itemCategory/test/fixtures.ts, src/services/item/plugins/itemCategory/test/index.test.ts, src/services/item/plugins/publication/published/test/index.test.ts, src/utils/repositories.ts
* refactor(CategoryRepository): removes unused get() method
=> refactor(CategoryRepository): extends AbstractRepository

src/di/container.ts, src/services/item/plugins/etherpad/service.ts, src/services/item/plugins/importExport/service.test.ts, src/services/item/plugins/importExport/service.ts, src/services/item/plugins/importExport/utils.ts
=> feat: allow exporting etherpad

package.json, src/services/item/plugins/importExport/index.ts, yarn.lock
Frontend needs to `decodeURI`. Look at https://stackoverflow.com/questions/46105398/header-content-contains-invalid-characters-error-when-piping-multipart-upload
=> feat: sanitize filename

src/services/itemMembership/repository.ts, src/services/itemMembership/utils.ts
@Defferrard this should fix your sonarCloud issues. It should also improve the code's reliability.
fix #1403
=> chore: update code to fix sonar cloud issue

src/services/itemMembership/repository.ts, src/services/itemMembership/utils.ts
Just some docs that I wrote last Friday, so we don't lose theses explanations in the future.
=> docs: move house keeping  behavior

src/schemas/ajvFormats.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/magicLink/schemas.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/mobile/schemas.ts, src/services/member/controller.test.ts, src/services/member/schemas.ts
Fixes #1311
Related PRs : https://github.com/graasp/graasp-account/pull/356 https://github.com/graasp/graasp-auth/pull/457
=> fix: do not allow special characters in username

.github/workflows/test.yml, package.json, src/services/itemLogin/service.ts, src/services/itemLogin/test/index.test.ts, yarn.lock
!!! NEED TO REBASE
`test.yml` got changed to run tests.
fix #1466
=> fix: save membership on item login schema item on item login

.aws/graasp-dev.json, .aws/graasp-prod.json, .aws/graasp-stage.json
In this PR I update the staging and prod task definition templates.
=> build: update task defs for stage and prod

src/services/item/test/index.read.test.ts, src/services/item/test/index.update.test.ts
=> refactor: have only one build for item tests

src/services/authorization.test.ts, src/services/chat/test/chatMention.test.ts, src/services/item/plugins/document/document.test.ts, src/services/item/plugins/file/test/index.test.ts, src/services/item/plugins/geolocation/index.test.ts, src/services/item/plugins/importExport/service.test.ts, src/services/item/plugins/importExport/test/index.test.ts, src/services/item/plugins/publication/published/test/index.test.ts, src/services/item/test/index.update.test.ts
=> refactor: use one build per tests

src/services/auth/plugins/mobile/schemas.ts
I started completing the schemas, let me know what you think ^^
=> docs: complete mobile schema

src/services/action/services/action.test.ts, src/services/item/plugins/action/service.test.ts, src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/itemFavorite/test/index.test.ts, src/services/item/plugins/publication/validation/test/index.test.ts
=> refactor: refactor tests to use one app build

src/services/auth/plugins/password/index.test.ts, src/services/auth/plugins/password/service.ts
=> fix: password reset token should be single use

src/services/auth/plugins/password/index.test.ts, src/services/auth/plugins/password/index.ts
=> fix: do not encode redirection url for password

src/services/chat/index.ts, src/services/chat/schemas.ts, src/services/item/plugins/itemFlag/schemas.ts, src/services/item/plugins/itemLike/index.ts, src/services/item/plugins/itemLike/schemas.ts
Added documentation for some routes. 
Removed and renamed when necessary.
=> docs: add documentation to routes

src/services/member/schemas.ts, src/services/member/test/index.test.ts, src/services/member/test/setup.ts, test/setup.ts
Based on  https://github.com/graasp/graasp/pull/1539
fix #1534
=> fix: update schema for current account

.aws/graasp-dev.json, .aws/graasp-prod.json, .aws/graasp-stage.json
Partially revert changes from #1519 
close #1559
=> fix: put nudenet back in container

src/services/item/plugins/invitation/index.ts, src/services/item/plugins/invitation/schema.ts, src/services/item/plugins/invitation/test/index.test.ts, src/services/member/schemas.ts
=> feat: split upload csv

package.json, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/repository.ts, src/services/item/test/index.update.test.ts, yarn.lock
Use item lang in meilisearch.
ref #800
=> feat: add item lang in meilisearch index

src/services/item/plugins/itemFavorite/index.ts, src/services/item/plugins/itemFavorite/schemas.ts, src/services/item/plugins/itemLike/schemas.ts, src/services/itemLogin/schemas.ts
=> docs: add documentation for item favorite, small refactor

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml
Env varaibles were not set correcly
=> fix: add env var for account

src/services/item/plugins/app/appAction/schemas.ts, src/services/item/plugins/app/appData/index.ts, src/services/item/plugins/app/appData/schemas.ts, src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/app/appSetting/index.ts, src/services/item/plugins/app/appSetting/schemas.ts, src/services/item/plugins/app/index.ts, src/services/item/plugins/app/schemas.ts
=> docs: add openapi documentation for app schemas

src/services/chat/plugins/mentions/index.ts, src/services/chat/plugins/mentions/schemas.ts
=> docs: add documentation for mention

src/migrations/1729857146775-item-category-to-item.ts, src/migrations/1729857146775-migrations.ts
=> feat: add migration from item category to item lang

src/services/item/plugins/invitation/schema.ts
=> docs: add docs for invitation endpoints

src/services/member/plugins/profile/controller.ts, src/services/member/plugins/profile/schemas.ts
=> docs: add docs for member profile endpoints

src/services/item/plugins/recycled/index.ts, src/services/item/plugins/recycled/schemas.ts, src/services/item/plugins/recycled/test/index.test.ts
=> docs: add docs for recycled item endpoints

src/services/item/plugins/app/chatBot/index.ts, src/services/item/plugins/app/chatBot/schemas.ts
=> docs: add docs for app chatbot endpoint

src/services/item/plugins/file/index.ts, src/services/item/plugins/file/schema.ts
=> docs: add documentation for file endpoints

src/services/item/plugins/importExport/schema.ts, src/services/item/plugins/importExport/test/index.test.ts
=> docs: add docs for zip import and export endpoints

src/services/item/plugins/app/appData/plugins/file/index.ts, src/services/item/plugins/app/appData/plugins/file/schema.ts, src/services/item/plugins/app/appSetting/plugins/file/index.ts, src/services/item/plugins/app/appSetting/plugins/file/schema.ts
=> docs: add docs for app data file endpoints

src/services/itemLogin/index.ts, src/services/itemLogin/schemas.ts
=> docs: add docs to item login endpoints

src/services/auth/plugins/magicLink/schemas.ts, src/services/item/plugins/enroll/schema.ts
=> docs: add documentation for magiclink

src/services/item/plugins/shortLink/schemas.ts
=> docs: add documentation for short links

src/services/itemMembership/index.ts, src/services/itemMembership/schemas.ts
I ignored GET many memberships since I will change it in another PR.
ref #1528
=> docs: add schemas to item membership endpoints

src/services/item/plugins/enroll/index.ts, src/services/item/plugins/enroll/service.ts, src/services/item/service.ts, src/services/itemMembership/service.ts
Create EnrollService to be able to use repositories when needed (get item without permission, create membership without permission).
Next steps would be to remove `throwOnForbiddenPermission` for get items in ItemService.
Added some `private`.
=> refactor: refactor enroll endpoint

src/services/item/plugins/tag/Tag.repository.test.ts
Some tests are not passing, I don't know why it got merged tho.
=> fix: fix tests

src/services/item/plugins/publication/published/schemas.ts
=> fix: add documentation and details to published schemas

src/app.ts, src/services/item/plugins/tag/ItemTag.repository.test.ts, src/services/item/plugins/tag/ItemTag.repository.ts, src/services/item/plugins/tag/constants.ts, src/services/item/plugins/tag/controller.test.ts, src/services/item/plugins/tag/controller.ts, src/services/tag/controller.test.ts, src/services/tag/controller.ts, src/services/tag/schemas.ts, src/services/tag/service.ts
I've added `/tags?search=<search>&category=<category>`where search is mandatory, and category is optional.
close #1647
=> feat: add tag count search

.vscode/settings.json, src/services/auth/plugins/magicLink/index.ts, src/services/file/interfaces/fileRepository.ts, src/services/file/repositories/local.ts, src/services/file/service.ts, src/services/file/utils/errors.ts, src/services/item/plugins/action/requestExport/service.ts, src/services/item/plugins/app/appData/plugins/file/service.ts, src/services/item/plugins/app/appSetting/plugins/file/service.ts, src/services/item/plugins/file/service.ts, src/services/item/plugins/file/test/index.test.ts, src/services/item/plugins/html/service.ts, src/services/item/plugins/importExport/service.ts, src/services/item/plugins/invitation/service.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/validation/moderators/imageValidationStrategy.ts, src/services/member/plugins/export-data/utils/export.utils.ts, src/services/thumbnail/service.ts
In this PR:
- remove unused id passed to `getUrl` function
=> fix: file id error

package.json, src/migrations/1733751673963-remove-display-name.ts, src/services/item/entities/Item.ts, src/services/item/plugins/file/service.ts, src/services/item/repository.ts, src/services/item/schemas.create.ts, src/services/item/schemas.ts, src/services/item/test/index.update.test.ts, src/services/item/utils.ts, src/services/member/plugins/export-data/schemas/schemas.ts, test/mocks/sampledatas.ts, yarn.lock
Update and remove display name given updates in sdk.
=> feat: remove display name

src/services/item/plugins/action/service.test.ts, src/services/item/plugins/app/appAction/repository.ts, src/services/item/plugins/tag/ItemTag.repository.test.ts
=> fix: add item in app action

package.json, src/logger.ts, src/plugins/mailer/test/index.test.ts, src/plugins/meta.ts, src/services/action/utils/export.test.ts, src/services/auth/plugins/password/index.test.ts, src/services/chat/repository.ts, src/services/chat/test/chatMention.test.ts, src/services/item/plugins/html/h5p/test/helpers.ts, src/services/item/plugins/importExport/test/index.test.ts, src/services/item/plugins/shortLink/test/fixtures.ts, src/services/item/plugins/shortLink/test/index.test.ts, src/services/item/plugins/tag/ItemTag.repository.ts, src/services/item/test/fixtures/items.ts, src/services/item/test/index.update.test.ts, src/services/itemLogin/test/index.test.ts, src/services/member/plugins/action/test/index.test.ts, src/services/member/plugins/action/test/service.test.ts, src/services/member/plugins/action/test/utils.ts, src/utils/assertions.ts, test/migrations/1692624998160-category-seed/migrations.test.ts, yarn.lock
Fix types at different places to slowly move to `strict: true`
ref #1693
=> refactor: fix types

src/migrations/1734623784243-downgrade-guest-memberships.ts, src/migrations/1734623784243-migrations.ts
=> fix: add migration for downgrading guest memberships

src/services/item/plugins/publication/published/plugins/search/meilisearch.ts
Apply facet settings after rebuild, on current index
=> fix: update facet settings after rebuild

src/services/item/index.ts, src/services/item/plugins/document/controller.test.ts, src/services/item/plugins/document/controller.ts, src/services/item/plugins/document/schemas.ts, src/services/item/plugins/document/service.test.ts, src/services/item/plugins/document/service.ts
Add POST and PATCH for documents.
Sanitize content for both.
ref #1710
=> feat: add document endpoints

package.json, src/migrations/1736512586095-item-like-index-item.ts, src/services/action/entities/action.ts, src/services/item/plugins/itemLike/index.ts, src/services/item/plugins/itemLike/itemLike.ts, src/services/item/plugins/itemLike/repository.test.ts, src/services/item/plugins/itemLike/repository.ts, src/services/item/plugins/itemLike/service.test.ts, src/services/item/plugins/itemLike/service.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/schemas.ts, src/services/item/plugins/publication/published/test/meilisearch.test.ts, yarn.lock
Add likes property in meilisearch, so it can be fetched to be displayed on the cards.
ref #1714
=> feat: add likes in meilisearch

src/services/item/plugins/etherpad/controller.ts, src/services/item/plugins/etherpad/schemas.ts, src/services/item/plugins/etherpad/service.test.ts, src/services/item/plugins/etherpad/service.ts, src/services/item/service.ts
=> feat: allow readers to edit etherpad

src/services/item/plugins/publication/validation/index.ts, src/services/item/plugins/publication/validation/schemas.ts
=> feat: improve schemas for item validation

src/services/action/test/fixtures/actions.ts, src/services/file/repositories/s3.ts, src/services/item/plugins/file/index.ts, src/services/item/plugins/folder/controller.test.ts, src/services/item/plugins/folder/service.test.ts, src/services/item/plugins/folder/service.ts, src/services/item/plugins/publication/validation/index.ts, src/services/item/plugins/publication/validation/utils.ts, src/services/member/plugins/profile/test/index.test.ts, src/services/tag/Tag.repository.test.ts
- Fix some typings.
- Add `get` a Folder Item
ref #1693
=> refactor: improve typings, get folder item

src/services/item/index.ts, src/services/item/plugins/app/appItemService.test.ts, src/services/item/plugins/app/appItemService.ts, src/services/item/plugins/app/controller.test.ts, src/services/item/plugins/app/controller.ts, src/services/item/plugins/app/schemas.ts, src/services/item/plugins/embeddedLink/service.test.ts, src/services/item/plugins/embeddedLink/service.ts, src/services/member/plugins/thumbnail/schemas.ts
=> feat: add app endpoints

src/services/item/plugins/folder/controller.test.ts, src/services/item/service.test.ts, src/services/member/controller.test.ts, src/services/member/test/index.test.ts, test/mocks/seed.ts
Replace save functions with seed.
=> refactor: use seed for member controller tests

src/repositories/MutableRepository.ts, src/sentry.ts, src/services/auth/plugins/passport/strategies/jwt.ts, src/services/auth/plugins/passport/strategies/magicLink.ts, src/services/file/repositories/local.ts, src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appSetting/plugins/file/service.ts, src/services/item/plugins/app/service.ts, src/services/item/plugins/etherpad/service.ts, src/services/item/plugins/geolocation/repository.ts, src/services/item/plugins/html/h5p/test/plugin.test.ts, src/services/item/plugins/shortLink/repository.ts, src/services/item/service.ts, src/services/itemLogin/repositories/itemLoginSchema.ts, src/services/itemMembership/repository.ts, src/services/member/repository.test.ts
=> refactor: fix types for `strict: true`

src/services/item/plugins/app/appData/plugins/file/index.ts, src/services/item/plugins/app/appData/service.ts
=> refactor: remove hook for app data file on patch

package.json, src/services/auth/utils.ts, yarn.lock
=> feat: redirect to home

src/services/item/plugins/embeddedLink/controller.test.ts, src/services/item/plugins/embeddedLink/schemas.ts
Allow settings to be patch in link patch endpoint. Update test for integration.
=> fix: allow link settings to be patched

src/services/item/plugins/file/index.ts, src/services/item/plugins/file/schema.ts, src/services/item/plugins/file/service.ts, src/services/item/plugins/file/test/index.test.ts, src/services/item/service.ts
=> feat: add patch file

src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/enroll/index.test.ts, src/services/itemLogin/test/fixtures.ts, src/services/itemLogin/test/index.test.ts, src/services/itemMembership/test/index.test.ts, src/services/member/entities/member.test.ts, src/services/member/plugins/thumbnail/test/index.test.ts, test/factories/member.factory.ts, test/mocks/seed.ts
=> refactor: refactor item login test with seed

src/drizzle/operations.ts, src/drizzle/schema.ts, src/services/item/item.repository.ts, src/services/item/plugins/geolocation/itemGeolocation.repository.ts, src/utils/config.ts
Adds full text search to accessible, children and map items endpoints.
- No index, it doesn't seem to use it. Probably because the join removes a lot of entries beforehand.
- Reusable search operation functions
=> feat: add full text search

src/services/item/plugins/app/appData/appData.controller.test.ts, src/services/item/plugins/app/appData/appData.controller.ts, src/services/item/plugins/app/appData/appData.service.ts, src/services/item/plugins/app/appData/test/legacy.test.ts
Add back member info in app data, as it's still legacy.
=> fix: add member prod to app data

.github/actions/build-images/action.yml, .github/workflows/release-please.yml
There was some bits and pieces missing in the release please workflow
=> fix: release please workflow

src/services/chat/chatMessage.schemas.ts, src/services/chat/plugins/mentions/chatMention.schemas.ts, src/services/item/plugins/app/appSetting/appSetting.controller.test.ts, src/services/item/plugins/app/appSetting/appSetting.controller.ts, src/services/itemMembership/membership.repository.test.ts, src/services/itemMembership/membership.repository.ts
=> fix: copy app settings on item copy

src/app.ts, src/drizzle/0004_maintenance.sql, src/drizzle/meta/0004_snapshot.json, src/drizzle/meta/_journal.json, src/drizzle/schema.ts, src/services/item/item.repository.ts, src/services/maintenance/maintenance.controller.test.ts, src/services/maintenance/maintenance.controller.ts, src/services/maintenance/maintenance.repository.test.ts, src/services/maintenance/maintenance.repository.ts, src/services/maintenance/maintenance.schemas.ts, src/services/maintenance/maintenance.service.ts
=> feat: add get maintenance endpoint

package.json, src/services/item/item.schemas.packed.ts, src/services/item/plugins/importExport/test/index.test.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/search.schemas.ts, src/services/item/plugins/publication/published/plugins/search/search.service.ts, src/services/item/plugins/tag/ItemTag.repository.test.ts, src/services/item/plugins/tag/itemTag.service.ts, src/services/tag/tag.repository.test.ts, src/services/tag/tag.repository.ts, yarn.lock
In this PR, I update the schema for search and item_packed to amke them work better with the generation.
=> fix: improve schemas for item_packed.thumbnails and search hits

src/services/action/utils/export.test.ts
Fix test for export actions to fix lint errors.
The test is not exhaustif, but it tests it creates the right number of files in the tmp folder.
=> refactor: fix export actions test

README.md
=> fix: some typo in the readme

.github/workflows/release-please.yml
=> fix: remove legacy push action to graasp-deploy

.devcontainer/devcontainer.json, package.json, src/services/item/plugins/app/chatBot/chatBot.controller.test.ts, src/services/item/plugins/app/chatBot/chatBot.service.ts, src/services/item/plugins/app/chatBot/openAICompletion.ts, src/services/item/plugins/app/chatBot/utils.ts, src/utils/config.ts, yarn.lock
We first need to apply #1920 before we can continue on this PR.
=> fix: upgrade openai models

test/factories/item.factory.ts
Fix a code smell detected by sonar-cloud related to nested template strings
=> fix: code smell with nested template string
