graasp/graasp

.devcontainer/docker-compose.yml
Whenever you want to run the core locally outside of the container, it is necessary to have this for the app to recognize the redis port. It is a frequent issue with the m1 chip.
It is not harmful to have this forwarding as all of the rest of the services have them.
=> refactor: include redis port forwarding

README.md
This PR adds documentation for the Migrations so users don't have to look for them in each repo.
They will need to be kept up to date, this is why the link to the migrations folder of the repo is provided first and the individual links for migrations are provided as convinience.
In the future it would be nice to have an automated way of performing the migrations and installation of the database. In the meantime we can try to keep the Readme up-to-date.
closes #234
=> doc: add migrations in readme

.github/workflows/cdelivery-ecs-backend-caller.yml, .github/workflows/cdeployment-ecs-backend-caller.yml, .github/workflows/cintegration-ecs-backend-caller.yml, .github/workflows/update-staging-version.yml, README.md
In this PR we change the version of the re-usable workflows used to be `v1`. This is considered less secure than using the commit sha, but it will save on maintainance as we will not have to worry about updating the sha for every new commit in graasp/deploy. 
Alternatively we could use the minor tag `v1.1` for less flexibility.
I also added a badge to the readme to show the current version.
closes #271
=> chore(ci): update the workflow version used

yarn.lock
This PR hotfixes a bug with adding apps and receiving a failure from server. This was caused by a `Promise.all` call in the graasp-plugin-thumbnail posthook handler on the createItemTask for apps.
closes #292
=> fix: update plugin-thumbnails

package.json, yarn.lock
Ensure that graasp-plugin-thumbnails and graasp-plugin-file-item do not resolve to the latest versions implemented by #287. Instead, use their respective latest commit before the fix.
:warning: the hash is fixed in the resolutions, so make sure to remove the hardcoded values in the future when thumbnails is working properly
=> fix: pin graasp-plugin-thumbnails and graasp-plugin-file-item

src/services/items/db-service.ts
close #304 
I couldn't think of another way of filtering the items through sql. 
The filtering function could be optimized (I'm thinking of sorting by path, then one loop comparing the shortest path and current path, filter out if the current path is a children of the shortest path).
=> fix: return shared sibling items

package.json, src/app.ts, src/services/item-memberships/ws/hooks.ts, src/services/items/ws/hooks.ts, yarn.lock
TODO: some other plugins are depending on websockets - check that they do not point to old repo name anymore (lookup "graasp-websockets" in yarn.lock)
=> feat: update graasp-plugin-websockets 

.aws/refactor.json, .github/workflows/deploy-refactor.yml
This PR adds a first version of the deployment workflow for the refactor.
The idea is to duplicate the environment (new h5p container, new s3 file buckets, etc).
Only the mail service will be the same.
close #338
=> refactor: add deploy refactor workflow

package.json, yarn.lock
This fixes opening multiple etherpads in the same context
=> fix: bump @graasp/plugin-etherpad

package.json
Using the existing `--check` flag of TypeORM's `migration:generate` is better than doing `schema:log` because it actually returns an 1 error code when there is syncing error between database state and code entities. This make the CI fails when some migrations are missing.
In this PR workflow we have an example of the CI failing because the current version of the `typeorm` branch is missing one constraint in the migrations: https://github.com/graasp/graasp/actions/runs/5078366591/jobs/9122791219#step:9:66
I made a temporary branch after running `migration:generate` to add missing migration and show that the check step pass in this case:  https://github.com/graasp/graasp/actions/runs/5078483639/jobs/9123045651#step:9:49
=> chore: check migration sync status with code

src/services/file/repositories/s3.ts, src/utils/config.ts
This config seems seems to have disapeared on the `typeorm` branch. Adding them back allows me to upload files on local dev.
I expect the endpoint to default to the real S3 when it's undefined but maybe i'm missing something?
=> fix: localstack error during local dev

src/services/item/controller.ts, src/services/item/plugins/action/service.ts, src/services/item/plugins/h5p/test/plugin.test.ts
* bundling the action and item modification in the same transaction
* is there a reason not to do this that I missed?
* adding await inside transactions, this is what is recomended in the docs
* ![image](https://github.com/graasp/graasp/assets/14032127/f7aa2417-e38c-404c-9c45-141761e67100)
* awaiting the transaction themselve is debatable depending on our needs
waiting to see if it doesn't break the CI in other places
=> Fix item controller

.husky/post-checkout
This PR removes the `postcheckout` husky hook as it caused unwanted installs when rebasing, checking out other branches etc.
It has been evaluated it was more cumbersome thatn helpful, so it is removed.
=> chore: delete postcheckout husky hook

package.json, src/migrations/1683637099103-add-favorites.ts, src/plugins/__mocks__/datasource.ts, src/plugins/datasource.ts, src/services/item/index.ts, src/services/item/plugins/itemFavorite/entities/ItemFavorite.ts, src/services/item/plugins/itemFavorite/errors.ts, src/services/item/plugins/itemFavorite/index.ts, src/services/item/plugins/itemFavorite/repositories/favorite.ts, src/services/item/plugins/itemFavorite/schemas.ts, src/services/item/plugins/itemFavorite/services/favorite.ts, src/services/item/plugins/itemFavorite/test/index.test.ts, src/utils/repositories.ts, test/migrations/migrations1683637099103/fixture.ts, test/migrations/migrations1683637099103/migrations.test.ts, yarn.lock
Based on branch `typeorm`
Related PRs:
* SDK: https://github.com/graasp/graasp-sdk/pull/164
* query-client: https://github.com/graasp/graasp-query-client/pull/275
* Builder: https://github.com/graasp/graasp-builder/pull/656
Favorite items used to be a field in the extra field of members. This PR is making it a real entity of the relational database model. This implies some migrations to handle the existing data and creating the new table.
Once everything is reviewed, this can be merged on typeorm, or this can wait for the refactor merge to be merged on main.
=> feat: refactor favorite items

src/migrations/1679669193721-migrations.ts, test/migrations/migrations1679669193721/migrations1679669193721.fixtures.ts
The fix takes into account:
- item that might not exist anymore
- uses `item_id`  that is more accurate than `item_path` (since `item_path` was not constrained https://github.com/graasp/graasp-plugin-recycle-bin/commit/5e461b796070d49782b47fc60d74b2ae3d75ad7c )
I didn't write regression tests because this case only exists because the staging env very probably uses an outdated db schema. The base schema we use for the tests (`migrations1679669193720`) contains the constraint so the error cannot happen.
close #404
=> fix: fix migrations for recycled items

src/services/item/plugins/itemLike/service.ts, src/services/item/plugins/itemLike/test/index.test.ts, src/services/item/plugins/itemLike/test/utils.ts, src/services/item/plugins/published/index.ts, src/services/item/plugins/published/repositories/itemPublished.ts, src/services/item/plugins/published/schemas.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts, src/utils/config.ts
I've implemented an endpoint to get the most liked items for the library.
I couldn't make it work to consider child of published items, but I guess it's not really important currently.
close #395
=> feat: add get most liked collections endpoint

src/services/itemMembership/service.ts, src/services/itemMembership/test/index.test.ts, src/utils/errors.ts
This PR checks that on deletion of an item membership, the user is not the last admin on the associated item. If that's the case, the server throws a bad request instead (is there a better status code?).
Closes #384
=> fix: prevent deletion of only / last admin on item

.devcontainer/docker-compose.yml, .devcontainer/localstack/init.sh, src/services/item/plugins/published/repositories/itemPublished.ts
This PR adds the creator field to the returned published items.
~~Maybe we should filter the properties of the member that are returned ? But this would mean we have to create a new `PublicMember` type that only contains information that is ok to share. I do not know how we would handle that with relation to the type that is defined on the relation ... Maybe there is a way to filter the data directly using typeorm ? Like only exporting certain allowed columns ?~~
Update: The creator properties are handled by the schema, only "id", "name" and "email" are allowed, so we are fine. 😄 
This change is needed for the user avatars to work in the library.
=> fix: return creator for published items

.gitignore, src/services/item/plugins/itemTag/repository.ts, src/services/item/plugins/published/repositories/itemPublished.ts, src/services/item/plugins/published/test/index.test.ts
This PR updates the publish information call to return the root item when querying for a child item that is published.
- single call
- multiple call
=> fix: return root published item when querying for a child item

src/migrations/1689666251815-clean-tags.ts, test/migrations/migrations1689666251815/fixture.ts, test/migrations/migrations1689666251815/migrations.test.ts
Adds a sql query to remove duplicate tags, it happens only in dev (and stage) since we re-added public to some of the items.
=> fix: remove duplicate public tag in migration

README.md, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/utils/config.ts
This PR updates the `/m/login-password` endpoint to use a redirect and send the token as a query-param. 
This is to support the workflow of the mobile login from the webauth.
The deep-link uses the protocol set in the `GRAASP_MOBILE_BUILDER` env variable which defaults to `graasp-mobile-builder`.
We could mirror what is happenning with the web endpoints for the redirect url which can be set as a query param in the request, and the backend uses it if it is in the allowed whitelist.
=> fix: login-password to use a redirect with the token in query string

.github/workflows/test.yml, src/migrations/1689777747530-default-item-settings.ts, src/services/item/plugins/document/document.test.ts, src/services/item/plugins/document/schemas.ts, src/services/item/repository.ts, test/migrations/migrations1689666251815/migrations.test.ts, test/migrations/migrations1689777747530/fixture.ts, test/migrations/migrations1689777747530/migrations.test.ts
Closes #500 
- Adds test to check if multiple extra and settings fields can be modified
- Fix logic that checks which extra and settings can be updated
- Adds yarn check (for prettier) in CI
=> fix: allow multiple extra and settings fields on update

src/services/item/plugins/published/repositories/itemPublished.ts
This PR adds the relation "creator" for the recent and liked collections. This way it can be displayed in the library.
=> fix: add creator in recent and liked collections

package.json, src/services/authorization.ts, src/services/item/plugins/app/appAction/repository.ts, src/services/item/plugins/app/appData/appData.ts, src/services/item/plugins/app/appData/errors.ts, src/services/item/plugins/app/appData/index.ts, src/services/item/plugins/app/appData/repository.ts, src/services/item/plugins/app/appData/schemas.ts, src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/published/test/index.test.ts, test/migrations/migrations1689777747530/migrations.test.ts, yarn.lock
The every app data couldn't be fetch by the reader: we missed the `member` visibility app data.
- I've moved the permission logic to the repository. I've noticed `casl` abilities don't work so I've removed it from `appData` and `authorization` 
- For simplicity, and because we don't use it, I've removed the possibility to add filters for `GET /appData`
- `PATCH /appData` was also missing a throw check.  
- added member to `GET /appAction`
close #504
=> 504 fix app data reader

src/services/item/plugins/itemLike/itemLike.ts, src/services/item/plugins/itemTag/index.ts, src/services/item/plugins/itemTag/repository.ts
In this PR:
- fix: copied item does not inherit public tag from original
- fix: remove dependency on ItemLike in Entity
=> fix: copied item should not inherit public tag from original

src/services/item/plugins/published/repositories/itemPublished.ts
This PR fixes a missing call related to the issue fixed in #502 
The creator was not joined and thus was missing from the response.
=> fix: add creator in getPublishedItemsByCategories

src/services/item/controller.ts, src/services/item/entities/Item.ts, src/services/item/plugins/app/appSetting/plugins/file/index.ts, src/services/item/plugins/importExport/test/index.test.ts, src/services/item/service.ts, src/services/item/test/index.test.ts, src/services/item/ws/hooks.ts, src/services/itemMembership/entities/ItemMembership.ts, src/services/itemMembership/repository.ts, src/services/itemMembership/test/fixtures/memberships.ts, src/services/itemMembership/ws/hooks.ts
This error happens for the following case:
- A > B > C with a membership for each of them for another member Bob
- Removing B, by cascade all the memberships of B and C get deleted
- Since A still have a membership, it triggers the websockets "shared items"
- But since C is get via `getDescendants` which does not return the creator, it fails
In this PR:
- I've added `null` to item's creator and itemMembership's creator
- This highlighted the ws hooks that needed more check on these fields
- added a test
- added postHook for move 
close #526
=> fix: null creator in ws hooks

src/services/auth/index.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/magicLink/service.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/mobile/service.ts, src/services/auth/plugins/password/repository.ts, src/services/auth/service.ts, src/services/auth/utils.test.ts, src/services/auth/utils.ts, src/services/item/plugins/app/appSetting/repository.ts, src/services/item/plugins/itemCategory/errors.ts, src/services/item/plugins/itemCategory/repositories/category.ts, src/services/item/plugins/itemLike/repository.ts, src/services/item/plugins/validation/errors.ts, src/services/item/plugins/validation/repositories/itemValidation.ts, src/services/member/repository.ts, src/services/member/test/index.test.ts
This PR fix the undefined member id in token by:
- using the member repository `get` instead of raw `findOneById`
- refactor auth utils in a dedicated file + `AuthService` (probably we don't need the decoration anymore). It's still confused because we have many functions doing "similar" logic , but I've left major refactor for later
- regression tests + unit tests of auth utils
Additionally:
- All other functions using  `findOneById` have an additional check over id
close #543
=> fix: throw for undefined member id in token

src/declarations.d.ts, src/services/chat/index.ts, src/services/chat/plugins/mentions/index.ts, src/services/invitation/index.ts, src/services/item/controller.ts, src/services/item/plugins/app/index.ts, src/services/item/plugins/file/index.ts, src/services/item/plugins/importExport/index.ts, src/services/item/plugins/itemCategory/index.ts, src/services/item/plugins/itemFlag/index.ts, src/services/item/plugins/itemLike/index.ts, src/services/item/plugins/itemTag/index.ts, src/services/item/plugins/published/index.ts, src/services/item/plugins/published/plugins/search/index.ts, src/services/item/plugins/thumbnail/index.ts, src/services/itemLogin/index.ts, src/services/itemMembership/index.ts, src/services/member/plugins/thumbnail/index.ts, test/app.ts
`fetchMemberInSession` only checked the cookie value.
Whereas `attemptVerifyAuthentication` does both `fetchMemberInSession` + `verifyBearerToken` which allows request to correctly get the member from the `Bearer` Authorization.
This effected all the public endpoints (ie. get item, get tags, etc)
close #550
=> fix: allow bearer token by using attemptVerifyAuthentication instead of fetchMemberInSession

src/services/item/plugins/app/appAction/index.ts, src/services/item/plugins/app/appAction/service.ts, src/services/item/plugins/app/appData/index.ts, src/services/item/plugins/app/appData/plugins/file/index.ts, src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appSetting/index.ts, src/services/item/plugins/app/appSetting/plugins/file/index.ts, src/services/item/plugins/app/appSetting/service.ts, src/services/item/plugins/app/ws/events.ts, src/services/item/plugins/app/ws/hooks.ts, src/services/item/plugins/app/ws/utils.ts
Use websockets to send events (post, patch, delete) on app data, actions and settings.
Refer to https://github.com/graasp/graasp-apps-query-client/pull/142 for details.
=> Broadcast apps data change events with websockets

package.json, src/services/item/plugins/importExport/index.ts, src/services/item/plugins/importExport/service.ts, src/services/item/plugins/importExport/test/index.test.ts, yarn.lock
This PR refactor `/zip-export` to use `yazl`. This library is supposed to handle streams, so we don't need to download all the files temporarly.
Currently h5p still saves its own temporary file. But this can be handled in a refactor for the download method of `FileService`.
close #537 
close #516
=> fix: export a zip use stream

package.json, src/services/item/constants.ts, src/services/item/entities/Item.ts, src/services/item/fluent-schema.ts, src/services/item/plugins/app/appSetting/plugins/file/service.ts, src/services/item/plugins/file/service.ts, yarn.lock
This PR aligns the truncation length of uploaded file names to match the item name limit. The limit is now `500`.
=> fix: align file name truncation with item name limit

src/services/item/plugins/published/constants.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts, src/utils/config.ts
The link was broken because we provided a `URL` object in another `URL` object.
fix #594
=> fix: fix library link in email

src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/utils/config.ts
Closes #498 (re-opened after Apple's review)
=> fix: use custom deep link protocol for mobile login password response

src/services/item/plugins/published/plugins/search/meilisearch.ts, src/services/item/plugins/published/repositories/itemPublished.ts
This PR changes the pagination strategy in meilisearch to use limit and offset instead of hitsPerPage and page.
It also changes a usage of `.take()` in typeorm to be `.limit()`.
=> fix: use limit and offset for meilisearch pagination

src/services/file/repositories/s3.ts
This PR fixes an issue with the typings.
This fix is coherent with the input typing https://github.com/graasp/graasp/blob/20d59793c97ccf3beb83fb8be6cb7af94d0bdd98/src/services/file/service.ts#L58
=> fix(types): fileStream argument has incompatible typing

src/services/item/plugins/itemLike/repository.ts
~~This PR also corrects a wrong import from #640 which makes the build fail. [Ref](https://github.com/graasp/graasp/pull/640#discussion_r1355155818)~~
Explanation of the change:
We need to manually do the join on `item.creator` with the `member` table for the creator to be included in the response. TypeORM does not include nested relations by default.
Related PRs that previously fixed a similar issue: #502 #524
This bug was discovered from the "quote inside avatar" bug in the library:
=> fix: add `item.creator` in item like response

src/services/item/plugins/app/appSetting/repository.ts
In this PR I added the missing relation on `item` for the `GET app-setting` endpoint and improved the return type of repository functions
close #651
=> fix: add missing relations in appSettings

.github/workflows/test.yml, src/migrations/1702456572289-migrations.ts, src/migrations/1702552816415-appsetting-indexes.ts, src/services/item/plugins/app/appData/appData.ts, src/services/item/plugins/app/appData/index.ts, src/services/item/plugins/app/appData/repository.ts, src/services/item/plugins/app/appData/schemas.ts, src/services/item/plugins/app/appData/service.ts, src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/app/appSetting/appSettings.ts, src/services/item/plugins/app/appSetting/index.ts, src/services/item/plugins/app/appSetting/repository.ts, src/services/item/plugins/app/appSetting/schemas.ts, src/services/item/plugins/app/appSetting/service.ts, src/services/item/plugins/app/appSetting/test/index.test.ts
In this PR I add the possibility to query app settings by name. This is done with an optional query parameter. This will allow consumers of the API to get only the list of settings that have a specific name. This will let them type the array as having a specific type linked to that name. This should improve the DX when writing apps.
=> feat: allow to query app settings by name

package.json, tsconfig.test.json
This PR adds a tsconfig to typecheck the whole project to type errors are catched before doing the tests.
fix #744
=> fix: add test tsconfig and update type-check command

src/plugins/decorator.ts, src/services/file/index.ts, src/services/file/interfaces/fileRepository.ts, src/services/file/repositories/s3.ts, src/services/file/service.test.ts, src/services/file/service.ts, src/services/item/plugins/html/h5p/service.ts, src/services/item/plugins/html/service.test.ts, src/services/item/plugins/html/service.ts, src/services/item/plugins/importExport/index.ts, src/services/item/plugins/importExport/service.ts
This PR adds a logger to the fileService to remove the ugly `console.error` printouts in aws logs.
fix #699
=> fix: add logger to fileService

src/declarations.d.ts, src/services/auth/plugins/captcha/index.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/password/index.ts, src/services/auth/plugins/password/test/password.test.ts
In this PR:
- fix #394 by adding a parameter in `verifyCaptcha` which decides if a low score should fail the request or not.
=> fix: do not fail login with password if score is low

src/services/item/repository.ts, src/services/item/service.ts, src/services/item/test/index.test.ts
check for copy and move whether
=> fix: throw if item is not folder for copy move

src/services/item/controller.ts, src/services/item/fluent-schema.ts, src/services/item/interfaces/requests.ts, src/services/item/repository.ts, src/services/item/service.ts, src/services/item/test/index.test.ts, src/services/item/types.ts, src/services/itemMembership/repository.ts
Add the query parameter `types` to allow to filter by item types in GET /items/accessible and /items/:id/children.
=> feat: allow to filter out item by type in accessible

README.md
In this PR:
- fix #722 
- fix add documentation for how to use the second db when running tests locally
=> docs: testing env and localstack issues

src/services/item/plugins/published/schemas.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts
In this PR:
- update behaviour when querying an item publish information
- unchanged: published item is returned 
- **changed**: public item return 200 null
- unchanged: item that exists but is not public return 403 forbidden
This allows to change the data in the cache when un-publishing.
fix #818
=> fix: return 200 with `null` when item is not published instead of error

.devcontainer/docker-compose.yml, README.md, src/services/file/index.ts, src/services/file/repositories/local.ts, src/utils/config.ts
In this PR:
- fix #841 
- fix: use fullpath when reading file size locally
- fix: add a static file server for local files
I added a local files server for when you use the local file system.
This has the advantage that:
- files are local, they should stay between re-boots. they will be removed if you delete the graasp folder on your machine.
- the static server is there to simply serve the files. Before there was not way to access the files that were stored on the device. This tries to mimic how it works with signed urls from s3 but much simpler. 
- the static file server is very small.
Let me know what you think. Also if you think more documentation should be added to document this (dev) feature.
=> fix: local file bugs and add a localfiles server

src/plugins/meta.ts
Add CORS headers on `/status` endpoint to allow querying the status from Auth frontend.
=> fix: add CORS on status endpoint

.devcontainer/docker-compose.yml
This PR removed the exposed port `1025` and reduces it to be accessible only inside docker network. We do not need this port to be exposed publicly on the machine and it can be seen as a security vulnerability.
=> fix: do not expose port 1025 to the local machine

src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/mobile/schemas.ts, src/services/auth/plugins/mobile/service.ts, src/services/item/plugins/recycled/test/index.test.ts
I've added an endpoint to allows the user (authenticated with a valid token in mobile) to authenticate on web. Basically it validates your token, and set the corresponding session in the cookie.
I'll use it in mobile to display the map through Builder.
=> feat: add auth from mobile to web

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml
Fix a really bad oversight that caused production deploy to actually deploy code from the main branch instead of code from the specified tag. 
When deploying the backend to production using the repository dispatch event, the deployed code is not the one pointed by the tag passed as arguments, but the code present on the main branch at the time of deployment.
When refactoring the deployment workflows, I introduced this bug because I used the dev workflow as a starter.
When running the dev deployment workflow, it is usually run from within a branch (mostly main). This means that calling `actions/checkout` checks out the code from the branch from where it was run. Usually this is what you want.
But in the case of the production and staging deployments, this is not the case. The workflows are …
=> fix: deploy workflow checkout

.github/workflows/deploy-prod.yml, .github/workflows/deploy-stage.yml
I had forgotten to set the tag to checkout also in the deploy part of the action. This is not as bad, as only the task definitions are pulled. And they do not usually change that frequently. But for consistency we should checkout the same tag.
=> fix: workflows again

src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/password/service.ts, src/services/auth/plugins/password/test/password.test.ts
In this PR I fix a bug where calling `/login-password` with an email that is not associated with an account return `Account not found`.
To align with the behaviour of the `/login` endpoint it should return `Member not sign up`.
fix #940
=> fix: password login should return `MemberNotSignedUp` if email has no account

package.json, src/migrations/1712230247740-enable-save-actions.ts, src/migrations/1712241391870-enable-save-actions.ts, src/services/action/services/action.test.ts, src/services/action/services/action.ts, src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/auth/plugins/magicLink/schemas.ts, src/services/auth/plugins/mobile/index.ts, src/services/auth/plugins/mobile/mobile.test.ts, src/services/auth/plugins/mobile/schemas.ts, src/services/auth/plugins/mobile/service.ts, src/services/item/plugins/invitation/service.ts, src/services/member/entities/member.ts, src/services/member/repository.ts, src/services/member/schemas.ts, src/services/member/service.ts, src/services/member/test/index.test.ts, yarn.lock
This PR:
- allows new users to enable or disable saving actions
- existing users have enableSaveActions to null
- This allows to facilitate what to do with existing users like:
- Stop saving actions until they explicitly accept it
- Continue saving actions
- Also allows to ask the user to choose 
- This wouldn't be possible if default value would be set to false
- allows all users to update this option
- ensure that actions can't be saved if the option is not true (or null if wanted, should be decided)
=> feat: allow user to enable/disable saving actions

src/services/item/plugins/published/plugins/search/meilisearch.ts, src/services/item/plugins/published/repositories/itemPublished.test.ts, src/services/item/plugins/published/repositories/itemPublished.ts, src/services/item/plugins/published/service.ts, src/services/item/plugins/published/test/index.test.ts, src/services/item/plugins/published/test/meilisearch.test.ts, src/services/item/repository.test.ts, src/services/item/repository.ts, src/services/item/test/fixtures/items.ts, src/utils/repositories.ts
Resolves #958 
In this PR I try to optimize the get published collections for member.
This query is remarkably slow and is executed for the home page of the library in the first section. 
This is the query execution plan for the query before optimization:
The execution time is around ~~9 seconds~~ (2 seconds on a hot database probably because of caching), that is unacceptable
This is the execution plan of the new query:
Execution time is ~~2 seconds~~ (between 2 and 10 miliseconds on a hot DB), better ~~but not as good as it could be with some custom SQL queries~~ actually I compared and the "custom" query below does not run significantly faster than the Typeorm optimized query.
I attache below the query that could be used to reduce even further the execution time:
```sql
SELECT …
```
=> fix: optimize get published collections for member

src/services/item/plugins/embeddedLink/index.ts, src/services/item/plugins/embeddedLink/test/fixtures.ts
A set of tests was broken, but the code #1009 was merged in main using the merging queue.
This PR fix the url used in these broken tests.
=> fix(test): set a valid url in fixtures and remove html in response

.github/workflows/test.yml, src/plugins/__mocks__/datasource.ts, src/plugins/datasource.ts, src/sentry.ts, src/server.ts, src/services/websockets/service-api.ts, src/utils/config.ts, src/utils/debug.ts
The first implementation of #998 didn't solved the issue. Because environnement variables where still used before initialisation during test context.
I've moved every `process.env`declarations in `config.ts` file, so every time we need to fetch an environnement variable, we have to import the configuration file.
=> 998 env variables are used before initialised by dotenv

.devcontainer/Dockerfile
In this PR I add the gnupg2 package inside the dev-container image to allow signing commit with GPG keys inside the container.
fix #1038
=> chore: allow gpg signing inside container

API Collections/Auth/Mobile/Sign In.bru, API Collections/Item/Create Link Item.bru, API Collections/Item/Update Link Item.bru, API Collections/environments/Graasp Local.bru, src/services/item/plugins/embeddedLink/index.ts, src/services/item/plugins/embeddedLink/schemas.ts, src/services/item/plugins/embeddedLink/test/embeddedLink.test.ts, src/services/item/plugins/importExport/test/fixtures/archive.ts, src/services/item/plugins/importExport/test/index.test.ts, src/services/item/service.ts, yarn.lock
In this PR:
- move automatic link description to the `extra.description` field
- allow to update a link `url`
- do not allow to update more that the `extra.url` field in updates to prevent injecting into the unsafe `extra.html` prop
fix #1057
=> fix: allow to update link url and disallow editing html

src/services/item/repository.test.ts, src/services/item/repository.ts
Using the `global` flag on a regex makes it stateful, which is not what we want in our case. 
I added a test and fixed the issue by removing the global flag.
=> fix: copy suffix can't increment past 3

src/services/item/plugins/embeddedLink/schemas.ts, src/services/member/schema.test.ts, src/services/member/schemas.ts, src/services/member/test/index.test.ts
fix #1128 
- Increase the tolerance for TLD names up to 63 chars long (according to https://www.rfc-editor.org/rfc/rfc1034)
- Add unit test for the email regex
- App regression test for the `/members/search` endpoint with offending `.swiss` email
=> fix: email regex for `.swiss` emails

src/services/member/controller.test.ts
I've missed a change in the tests. Here the fix so it matches with the implementation.
=> fix: already taken email test result with a conflict

src/utils/config.ts, src/utils/errors.ts
In this PR I propose to send a more meaningful error when and env var is missing. 
I spent a good amount of time figuring out the origin of the issue. 
The server would not start, because a new env variable was missing, but the error made it look like there was an error somewhere else. 
I try to create a new error that gives more information and indicates that the issue comes from a missing env variable.
=> chore: add missing env var error, for better DX

API Collections/Auth/Mobile/Register.bru, API Collections/Member/Delete Current Member.bru, API Collections/Member/Patch Current Member.bru, API Collections/environments/Graasp Local.bru, package.json, src/plugins/datasource.ts, src/server.ts, src/services/auth/plugins/magicLink/index.ts, src/services/item/controller.ts, src/services/item/fluent-schema.ts, src/services/item/plugins/html/h5p/validation/h5p-validator.ts, src/services/item/test/index.test.ts, src/services/member/controller.ts, src/services/member/plugins/profile/controller.ts, src/services/member/plugins/profile/errors.ts, src/services/member/plugins/profile/repository.ts, src/services/member/plugins/profile/schemas.ts, src/services/member/plugins/profile/service.ts, src/services/member/plugins/profile/test/fixtures/profile.ts, src/services/member/plugins/profile/test/index.test.ts, src/services/member/plugins/profile/types.ts, src/services/member/schemas.ts, src/services/member/service.ts, src/utils/errors.ts, src/utils/repositories.ts, test/app.ts, yarn.lock
fix #1157 
In this PR:
- add `request.session.delete()` on /logout to ensure cookie is removed from the browser
- add types on schemas
- fix an AJV warning in the h5p schema by adding `allowUnionTypes: true` to the options
- deprecate `DELETE /members/:id` and add a new `DELETE `/members/current` instead 
- add the logout directly on these delete routes
- refactor the members profile plugin and routes to make the responses more consistent
- NO_CONTENT when there is nothing
- OK when there is data
- UNAUTHORIZED when not logged in
- move the memberProfile repository to a custom repository class
- experiment with the querybuilder for efficient queries, but these are not type-safe and lack transformations ... sad
=> fix: logout member on delete

src/services/item/utils.ts
Descendants does not return the correct order. In real context, typeorm actually returns strings, and they are not sorted correctly when representing numbers (1001 < 20).
=> fix: sort descendants as number

src/migrations/1718693920666-add-isvalidated-lastauthenticated.ts
set legacy members as validated members. New members will be not validated.
WARNING: we need to redo the migration in dev
=> feat: change last migration to set legacy data validation to true

src/services/item/plugins/publication/README.md, src/services/item/plugins/publication/publicationState/publicationState.ts, src/services/item/plugins/publication/publicationState/test/publicationState.test.ts
- also handle the state where the item is unpublished and outdated
This change allows the frontend to better differentiate an outdated validation when an item is published or unpublished (graasp/graasp-builder#1367)
=> feat: update the unpublished state

src/services/item/plugins/geolocation/repository.ts, src/services/item/repository.ts, src/services/item/test/index.test.ts, src/services/itemMembership/repository.ts
The search scope lacks brackets, so it's overriding all other conditions. I've added the brackets to
- accessible
- children
- get from geolocation
with regression tests.
=> fix: fix where scope on search

.aws/graasp-dev.json, .devcontainer/docker-compose.yml
The log group for dev is not the same as the one defined by the the infrastructure. I correct this in this PR.
fixes #1248
=> fix: log group in dev should be `ecs/graasp`

package.json, src/app.ts, src/plugins/swagger.ts, yarn.lock
The documentation is accessible on `/docs`
We should be able to seperate our route by service with titles
Apparently for some reason models at the end of the page are buggy.
=> feat: implement fastify swagger

src/repositories/MutableRepository.ts
Update the `updateOne` method to use `getOne` instead of `findOne` to ensure to return the updated entity with the same relations as in the `getOne`.
=> fix(MutableRepository): use getOne in updateOne

.vscode/settings.json
@Defferrard I think this fixes the issue where the tests are run as soon as you start the container. 
I had this configuration set in my personnal settings, I put it in the shared settings so it can be applied to everyone using it.
=> fix: set jest extension to run on-demand instead of watch

src/services/member/controller.ts, src/services/member/schemas.ts, src/services/member/test/index.test.ts
In this PR: 
- add stricter route for updating the current member under `PATCH /members/current` 
- deprecate the old route
ref #1397
=> fix: deprecate patch member use current member instead

src/services/action/utils/export-utils.test.ts, src/services/action/utils/export.ts, src/services/auth/plugins/password/index.ts, src/services/item/plugins/action/index.ts, src/services/item/plugins/action/schemas.ts, src/services/item/plugins/action/service.ts, src/services/member/controller.test.ts, src/services/member/controller.ts, src/services/member/plugins/thumbnail/index.ts
In this PR: I fix the structure of the apps file in the exported zip.
Now the structure is as follows:
- In JSON, there will be a single file `apps.json` that will contain:
```json
{
"actions": [ array of actions ],
"data": [ array of data ],
"settings": [ array of data ],
}
```
- In CSV, there will be 3 files, `app_actions.csv`, `app_data.csv` and `app_settings.csv` which will contain tabular data from all items.
=> fix: app actions structure is wrong for export

docker/Dockerfile, package.json, src/services/item/plugins/embeddedLink/utils.ts, yarn.lock
Bump resolution for `sodium-native` to `4.2.0`
Remove dependency `is-url-http` and use `url-http` instead as it requires an up-to-date version of `re2` which does not fail the build in docker
=> fix: remove dependency to fix deploy

.aws/graasp-dev.json
This changes the log group to match the one defined in the infrastructure
=> fix: update core container log group to match infra

.aws/graasp-dev.json
Need to update the deployment variables for `iframely` and `nudenet`:
- iframely URL: `http://localhost:8061` -> `http://graasp-iframely:8061`
- nundenet URL: `http://localhost:8080/sync` -> `http://graasp-nudenet:8080/sync`
Done for DEV env
ref https://github.com/graasp/graasp-infrastructure/pull/34
=> fix: extract nudenet and iframely as separate services

src/services/action/repositories/action.test.ts, src/services/chat/plugins/mentions/repository.test.ts, src/services/chat/test/chatMessage.test.ts, src/services/item/plugins/enroll/index.test.ts, src/services/item/plugins/invitation/test/index.test.ts, src/services/item/plugins/itemFlag/test/index.test.ts, src/services/item/plugins/itemTag/test/index.test.ts, src/services/item/plugins/recycled/test/index.test.ts, src/services/itemLogin/test/index.test.ts
- Keep only one app `build`, signed out.
- Sign in/mock authentication when necessary within tests.
- Keep only one `clearDatabase` when possible (ensure other tests not refactored work on a clean database). 
ref #1516
=> test: use only one build for tests

src/services/item/plugins/embeddedLink/schemas.ts, src/services/item/plugins/embeddedLink/test/controller.test.ts
=> fix: set html as optional for link metadata

src/services/item/plugins/app/appData/test/index.test.ts, src/services/item/plugins/app/schemas.ts, src/services/item/plugins/app/service.ts, src/services/item/plugins/app/test/index.test.ts, src/services/itemLogin/test/index.test.ts, src/services/member/test/fixtures/members.ts, src/services/member/test/setup.ts
Restrict `members` in schema to `account`.
Also fixed getting context as a guest.
fix #1553
=> fix: allow guests in members app context, allow to get context as guest

src/services/account/repository.test.ts, src/services/item/ItemWrapper.test.ts, src/services/item/ItemWrapper.ts, src/services/item/plugins/itemTag/test/fixtures.ts, src/services/item/test/index.read.test.ts
Packed returns tags such as `public` and `hidden`. But sometimes it does not return the correct one: we want to return the highest inherited tag. It happens because it depends on the array order (usually fetched from db). I've also added sorting for `createPackedItems`.
That will hopefully fix the flacky test. 
I don't think it's the best fix, I would prefer to order from the db, or actually get the correct tag right away from the db. 
With the packed we actually removed the use of `GET /tags` and so we can remove `ResultOf` from getting tags.
I would apply this fix first, then I will deprecate getting tags, and finally remove `ResultOf`. 
fix #1547
=> fix: fix packed tag

src/services/item/plugins/file/schema.ts, src/services/item/plugins/file/test/index.test.ts, src/services/item/schemas.ts
Added handling for local files. Also added a test, and removed a non-used fn.
PS: file edition is actually broken because the frontend sends the complete extra, while the backend only accepts editable fields. PR for the frontend: https://github.com/graasp/graasp-builder/pull/1552
=> fix: allow local file in update schema

package.json, src/migrations/1730995045487-new-tags.ts, src/plugins/datasource.ts, src/services/item/plugins/tag/ItemTag.entity.ts, src/services/item/plugins/tag/Tag.entity.ts, yarn.lock
Create entities and migrations for creating those tables.
The migration to go from `item.settings.tags` -> `tags` will be done after, when the ip is ready (otherwise we might miss some tags that are added in between).
I'm not fan of the naming `ItemToTag`, I think it should be `ItemTag`. Should we move the current `ItemTag` to `ItemStatus`?
close #1609
=> feat: add tag and item to tag entities

src/services/auth/plugins/magicLink/index.ts, src/services/auth/plugins/magicLink/magicLink.test.ts, src/services/item/plugins/action/test/ws.test.ts, src/services/item/plugins/invitation/index.ts, src/services/item/plugins/invitation/repository.ts, src/services/item/plugins/invitation/service.ts, src/services/item/plugins/invitation/test/index.test.ts, src/services/item/plugins/invitation/test/utils.ts, src/services/member/service.ts, src/services/member/test/register.test.ts
- Remove member hooks: only one use is to create memberships from invitations for the new registered emails
- Create invitation utils for tests.
- Move /register tests in its own file, with regular tests and related invitation creation tests.
=> refactor: remove member hooks

package.json, src/migrations/1733844120221-cc-license-values.ts, src/services/item/schemas.ts, yarn.lock
Hopefully fix 
```
GET /item-memberships
The value of 'item#/properties/settings/properties/ccLicenseAdaption' does not match schema definition.
```
close #1073
=> fix: remove deprecated values for cc licenses

package.json, src/services/item/controller.ts, src/services/item/errors.ts, src/services/item/index.ts, src/services/item/plugins/folder/controller.test.ts, src/services/item/plugins/folder/controller.ts, src/services/item/plugins/folder/schemas.ts, src/services/item/plugins/folder/service.test.ts, src/services/item/plugins/folder/service.ts, src/services/item/service.ts, src/services/item/test/index.update.test.ts, src/services/item/test/utils.ts, src/services/itemMembership/plugins/MembershipRequest/index.test.ts, yarn.lock
This PR is based on another PR: item schemas.
I'd like a very quick review, to discuss structure and endpoint paths.
I added the following endpoints
- POST /items/folder
- POST /items/folder/with-thumbnail
- PATCH /items/folder/id
I created a `FolderItemService` that extends `ItemService` so it can reuse the service's functions and attributes.
close #1623
=> feat: add post and patch item folder

.eslintrc, src/fastify.ts, src/plugins/typebox.ts, src/schemas/ajvFormats.ts, src/scripts/generateOpenAPI.ts, src/services/action/entities/action.ts, src/services/item/plugins/action/base-analytics.ts, src/services/item/plugins/action/index.ts, src/services/item/plugins/action/schemas.ts, src/services/item/plugins/action/service.ts, src/services/item/plugins/action/test/fixtures/actions.ts, src/services/item/plugins/action/test/index.test.ts, src/services/item/plugins/app/appAction/schemas.ts, src/services/item/plugins/app/appData/plugins/file/schema.ts, src/services/item/plugins/app/appData/schemas.ts, src/utils/debug.ts, tsconfig.json
In this PR: 
- fix some schema issues with the aggregation and action endpoints used by analytics.
Question:
@pyphilia Can you give me feedback on these issues:
- I have modified the appActionSchema definition in the analytics return since we do not return the deprecated `member` attribute in the data. Do you think I should instead create a "standard appAction schema" and then extend that one with the legacy `member` prop for use in the appAction endpoint ? So all other schemas that may build on top of appAction can use the "standard" instead of having to each time strip the legacy prop ?
- I have removed the `itemMemberships` props from the return. But we still retrieve it from the DB and process it. Ideally we would use a different function.Should this be done now, or later ? 
- I …
=> fix: analytics query schema error

src/services/item/plugins/publication/published/index.ts, src/services/item/plugins/publication/published/plugins/search/index.test.ts, src/services/item/plugins/publication/published/plugins/search/index.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/schemas.ts, src/services/item/plugins/publication/published/plugins/search/service.test.ts, src/services/item/plugins/publication/published/plugins/search/service.ts, src/services/item/plugins/publication/published/repositories/itemPublished.ts, src/services/item/plugins/publication/published/schemas.ts, src/services/item/plugins/publication/published/service.ts, src/services/item/plugins/publication/published/test/index.test.ts
- moved `/collections/liked` from published -> search 
- use meilisearch to get the most liked items
ref #1714
=> feat: update get liked collections with meilisearch

src/services/item/service.test.ts, src/services/item/service.ts, src/services/itemLogin/index.ts, src/services/itemMembership/plugins/MembershipRequest/index.ts
Remove hacky `throwOnForbiddenPermission` prop to use the repository instead.
Added tests for `get`.
=> refactor: remove usage of `throwOnForbiddenPermission` for item service get

src/services/action/services/action.test.ts, src/services/item/plugins/action/service.test.ts, src/services/item/plugins/document/service.test.ts, src/services/item/plugins/document/service.ts, src/services/item/plugins/embeddedLink/service.test.ts, src/services/item/plugins/embeddedLink/service.ts, src/services/item/plugins/embeddedLink/test/service.test.ts, src/services/item/plugins/etherpad/service.test.ts, src/services/item/plugins/folder/service.test.ts, src/services/item/plugins/folder/service.ts, src/services/item/plugins/geolocation/service.test.ts, src/services/item/plugins/itemVisibility/index.ts, src/services/item/plugins/publication/published/plugins/search/index.test.ts, src/services/item/plugins/publication/published/plugins/search/service.ts, src/services/item/service.test.ts, src/services/item/service.ts
Move hooks in item service directly.
- Index copied items if they are copied in a published item
- Copy hidden tags
ref #1635
=> refactor: remove copy post hooks

src/services/item/plugins/publication/published/plugins/search/index.test.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/schemas.ts, src/services/item/plugins/publication/published/plugins/search/service.test.ts, src/services/item/plugins/publication/published/plugins/search/service.ts, src/services/item/plugins/publication/published/schemas.ts
Allow creator id in filter for search in meilisearch. The goal is to use this call in library.
I didn't remove the current `/collections/<memberId>` because it is used by builder (packed collections). Because it requires packed info, it won't be so easy to replace with the search call. So it will require some changes from the front first to remove the call definitely.
ref #1714
=> feat(published-search): allow creator id filter

package.json, src/migrations/1736938402277-item-published-updated-at-.ts, src/services/item/plugins/itemLike/service.ts, src/services/item/plugins/publication/published/entities/itemPublished.ts, src/services/item/plugins/publication/published/index.ts, src/services/item/plugins/publication/published/plugins/search/index.test.ts, src/services/item/plugins/publication/published/plugins/search/index.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/schemas.ts, src/services/item/plugins/publication/published/plugins/search/service.ts, src/services/item/plugins/publication/published/repositories/itemPublished.test.ts, src/services/item/plugins/publication/published/repositories/itemPublished.ts, src/services/item/plugins/publication/published/schemas.ts, src/services/item/plugins/publication/published/service.test.ts, src/services/item/plugins/publication/published/service.ts, src/services/item/plugins/publication/published/test/index.test.ts, src/services/item/plugins/publication/published/test/meilisearch.test.ts, src/services/item/plugins/publication/validation/service.ts, src/services/item/plugins/tag/service.ts, src/services/item/service.ts, yarn.lock
- add props `publicationUpdatedAt` to `meilisearch`
- add `updatedAt` to `ItemPublished`
- Move `/collections/recent` endpoint to search to use meilisearch's search 
TODO
close #1714
=> feat: update recent endpoint to use meilisearch

src/services/item/plugins/publication/published/plugins/search/index.test.ts, src/services/item/plugins/publication/published/plugins/search/service.test.ts, src/services/item/plugins/publication/published/plugins/search/service.ts
Remove default sorting of `publicationUpdatedAt`, it will default again to relevancy.
=> fix: remove default sorting for search

src/services/member/plugins/profile/controller.test.ts, src/services/member/plugins/profile/controller.ts, src/services/member/plugins/profile/schemas.ts, test/mocks/seed.ts
Return 200 instead of 204 in order to return `null` for the frontend.
- Complete `seedFromJson` with `memberProfile`
- Use `seedFromJson` in `controller.test.ts` of member profile
=> fix: return 200 and null for empty member profile

src/services/item/plugins/embeddedLink/service.test.ts, src/services/item/plugins/embeddedLink/service.ts
Replace non classic spaces from link metadata:
-  non breaking spaces
- tab
- breaking spaces
close #1338
=> fix: replace non breaking spaces from link metadata title

src/services/itemMembership/test/index.test.ts, src/services/member/test/index.test.ts, test/factories/member.factory.ts, test/mocks/seed.ts
Adds membership management for `seedFromJson`.
You can specify an `account` with a name only for a membership, that will generate a member correctly from it. Account are distinct by their name, so you can reuse the same name across one seed. 
This management does not handle `guest` yet.
=> refactor: use seed in membership tests

src/services/file/service.ts, src/services/item/plugins/file/index.ts, src/services/item/plugins/file/schema.ts, src/services/item/plugins/file/test/index.test.ts, src/services/item/plugins/thumbnail/index.ts, src/services/member/plugins/thumbnail/index.ts, src/services/member/plugins/thumbnail/schemas.ts, src/services/member/plugins/thumbnail/test/index.test.ts
Remove `replyUrl` for
- GET items/thumbnails
- GET members/avatar
- GET item/download (item file)
We still keep the query param to prevent schema error, but it does nothing. 
The only and default behavior is to return a string which is the url of the file (s3 url).
close #1758 
close #1683
=> refactor: remove reply url from get item content and thumbnail

package.json, src/services/item/plugins/etherpad/controller.ts, src/services/item/plugins/etherpad/schemas.ts, src/services/item/plugins/etherpad/service.test.ts, src/services/item/plugins/etherpad/service.ts, src/services/item/plugins/etherpad/test/index.test.ts, src/services/item/plugins/etherpad/test/service.test.ts, yarn.lock
- POST /etherpad: allow to set `readerPermission`
- PATCH /etherpad/id: allow to set item's props (name, settings, lang)
close #1779
=> feat(etherpad): allow readerPermission on create, item props in update

package.json, src/services/file/repositories/s3.ts, src/services/item/plugins/file/service.ts, yarn.lock
I think it never worked in the first place, but duplicating pdf would trigger a download of the file once displayed. The error only happens for pdf, probably because we use a viewer.
The solution was to remove the set content-disposition (attachment) in s3.
Alongside I removed the set cache control policy, and fixed the build path that was wrong on copy. It would result in `xxxundefined`. It doesn't impact anything tho (except the download name of the file).
=> fix(file): keep extension on copy, remove content-disposition and cache control

src/services/item/plugins/recycled/repository.ts, src/services/item/plugins/recycled/test/index.test.ts
Quick fix/patch for the following problem: deleted nested children are not returned for GET /recycled because they don't have a direct membership. The test was working because it created a membership for the child.
An error happens because typeorm automatically adds `item_path = item.path` which is not what we want. And thus ignores children.
The proposed solution works (returns the children) but the `totalCount` is false because the filtering happens after getting items. The filtering is necessary because the *raw* sql returns duplicated "membership/item".
A true solution would be to "unique" results with sql. But since we are currently refactoring the repositories with drizzle, we are not going to change the full query now.
=> fix: return deleted child items in own recycled

src/services/action/utils/export.ts, src/services/item/plugins/action/requestExport/service.ts
Remove strange slashes in the filename by using timestamp of the date.
Adds '.zip' format to download name.
fix #1823
=> fix(export-actions): use timestamp for filenames, infer zip

src/drizzle/0003_use-timezone-in-items-account.sql, src/drizzle/meta/0003_snapshot.json, src/drizzle/meta/_journal.json, src/drizzle/schema.ts
In this PR, I alter the type of the timestamp columns for `item`, `account` and `membership_request` to include the timezone. This solves and issue in the serialization where the timestamp was not timezone aware and the frontend would interpret it as local time leading to wrong dates.
We can change other tables as well, and in the end it would be better to have all tables using `timestamp with time zone` for consistency.
=> fix: convert timestamp columns to include timezone

.github/actions/build-images/action.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/release-please.yml, docker/Dockerfile, docker/auth.sh, docker/build.sh, docker/compose.yml, src/plugins/meta.ts, src/utils/config.ts
In this PR I
- Split the `build.sh` script up into the AWS auth part and the docker build and push part
- add the aws region to use when building an image
- fix some left over changes to the prod deploy workflow
- add a `BUILD_TIMESTAMP` env var that is set at build time so we can get when the image was built on the `/version` endpoint
- fix the volume mount for the db init script in the docker compose for self hosting
When we merge to main, we build an image that we push to the private ECR of the dev environment.
It is tagged as `core-next`.
Every morning a workflow in infra is triggered and deploy this `core-next` with the migration.
So at the latest the next day, the changes will be on dev.
=> fix: auto-deploy

src/services/item/plugins/etherpad/etherpad.controller.test.ts, src/services/item/plugins/etherpad/etherpad.controller.ts
In this PR:
- fix #1860 
I added a test that check access is allowed for guests. The test run expected to fail: https://github.com/graasp/graasp/actions/runs/14833607651
and the fix that is expected to pass: https://github.com/graasp/graasp/actions/runs/14833641777
=> fix: allow guests to access etherpad

src/services/item/item.controller.ts, src/services/item/item.schemas.packed.ts, src/services/item/plugins/file/itemFile.controller.test.ts, src/services/item/plugins/file/itemFile.controller.ts, src/services/item/plugins/file/itemFile.schema.ts
Instead of a `ResultOf`, the endpoint throws an error if one exists. 
This return is a bit wrong, since some files might have still been uploaded. But it is easier for the frontend to correctly show errors.
The best solution would be to return `ACCEPTED` and deal with websockets to correctly return many status codes. But it requires some refactors (websockets, progress, refactor to use `uploadMany` instead of in serie, etc)
=> fix(files-upload): return simple error if exists

API Collections/Item/Memberships/Delete membership.bru, API Collections/Item/Memberships/Get Item memberships.bru, src/app.ts, src/services/item/index.ts, src/services/itemMembership/membership.controller.test.ts, src/services/itemMembership/membership.controller.ts, src/services/itemMembership/membership.schemas.ts, src/services/itemMembership/plugins/MembershipRequest/membershipRequest.controller.ts, src/services/itemMembership/plugins/MembershipRequest/membershipRequest.schemas.ts, src/services/itemMembership/ws/ws.test.ts
Move membership endpoints inside items to have the following route: `items/:id/memberships`
This allows to remove cors options.
=> feat: move membership endpoints

src/services/item/plugins/itemLike/itemLike.controller.test.ts, src/services/item/plugins/itemLike/itemLike.controller.ts, src/services/item/plugins/itemLike/itemLike.repository.ts, src/services/item/plugins/itemLike/itemLike.schemas.ts
In this PR:
- fix #1863 
- add return data to the `POST item like` 
- allow to post twice 
- add a test that ensures this is allowed
=> fix: allow to post twice a like on an item

docker/migrate.Dockerfile
In this PR I fix [an issue related to the use of the `node:latest` tag in the migration Docker file](https://sonarcloud.io/project/issues?open=AZZDc6BjseWYDCZo2X5D&id=graasp_graasp).
It is best practice to use a specific version in order to ensure consistency.
=> chore(sonar-cloud): use a fixed tag for the builder base image in the migration docker file

.github/workflows/test.yml, src/services/item/plugins/publication/published/plugins/search/search.controller.test.ts, src/services/item/plugins/publication/published/plugins/search/search.controller.ts, src/services/item/plugins/publication/published/plugins/search/search.schemas.ts, src/services/item/plugins/publication/published/plugins/search/search.service.test.ts, src/services/item/plugins/publication/published/plugins/search/search.service.ts, src/utils/config.ts
In this PR I propose to add an endpoint to get the featured collections.
This allows to call a sinlge route wihout needing prior knowledge from the frontend.
This also allows us to potentially apply custom sorting on the retrieved collections.
For this to work, we need to add an env varaiable in the backend that has the value of the Graasper user account.
Add `GRAASPER_CREATOR_ID` to env variables.
=> fix: add endpoint for featured collections

package.json, src/services/itemMembership/membership.repository.ts
I have noticed that this specific query is slow in production (500ms)
Looking at the code I could not justify why we were returning the account props, so I removed them.
Let me know if you think this is a mistake.
=> fix(opti): remove join on accountsTable for `getInheritedMany`

src/services/file/file.service.ts, src/services/file/repositories/s3.ts, src/services/file/sanitize.ts, src/services/thumbnail/thumbnail.service.ts
Documentation states it is better to use `stream.pipeline()` than `.pipe()`. It might definitely help for our memory usage issue. https://nodejs.org/en/learn/modules/how-to-use-streams#pipeline
A bigger change should be to remove the use of `archiver` to use `yazl`. This will be for a next PR, I guess built upon the queue.
=> fix: use pipeline instead of pipe

src/services/item/item.controller.update.test.ts, src/services/item/item.repository.test.ts, src/services/item/item.repository.ts, src/services/item/item.service.ts
- add `getChildrenWithCreator` opposed to `getChildren` so we don't leftjoin the creator when it is not necessary. This simplified `rescaleOrder`
- add `fixOrderForTree` which is a sql query that rescale and correctly set orders in a tree.
- apply `fixOrderForTree` before copying, ensuring the order for the copied.
=> fix: sanitize original order before copy

src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/search.constants.ts, src/services/item/plugins/publication/published/plugins/search/search.controller.test.ts, src/services/item/plugins/publication/published/plugins/search/search.schemas.ts
In this PR I make the validation schema stricter for the `/items/collections/search/facets?facetName=XXX` XXX will now check on valid values and throw a BadRequest error if it does not match the set of values. 
The allowed values are taken from the filterable attributes defined on the index. 
This change should:
- prevent errors with invalid parameters thrown by the search
- make the generation better by explicitly typing the input params
> [!NOTE]
> There was a big footgun in this PR, the tact that we are mocking the `meilisearch.ts` file in the test meant that the constant `FILTERABLE_ATTRIBUTES` did not exist ... and so the tests failed ... it took me a while to figure it out ...
=> fix: add strict facetName schema from filterable attributes

package.json, src/drizzle/0007_action_view_enum.sql, src/drizzle/meta/0007_snapshot.json, src/drizzle/meta/_journal.json, src/drizzle/schema.ts, src/services/action/action.service.ts, src/services/item/plugins/action/itemAction.schemas.ts, yarn.lock
In this PR:
- remove the "explorer" value from the `action.view` enum ⚠️ REQUIRES A MIGRATION ⚠️ 
- update sdk (code changes make the return type of getContextFromLink have a better type and it clashes with the current implementation)
fix #1900
=> fix: action.view migration to remove `explorer` and add `home` and `analytics`

src/jobs.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.test.ts, src/services/item/plugins/publication/published/plugins/search/meilisearch.ts, src/services/item/plugins/publication/published/plugins/search/search.controller.ts, src/services/item/plugins/publication/published/plugins/search/search.service.ts, src/workers/config.ts, src/workers/dashboard.controller.ts, src/workers/entrypoint.ts, src/workers/itemExportRequest.worker.ts, src/workers/searchIndex.service.test.ts, src/workers/searchIndex.service.ts, src/workers/searchIndex.worker.spec.ts, src/workers/searchIndex.worker.ts
Create a new worker to handle build index task.
Remove pre-task of fetching pdf content, as we do it on upload.
For now, it uses `MeilisearchWrapper` as dependency to index items. In the next PR, indexing item should be a job as well.
close #1927
=> feat: create build index worker

src/services/auth/plugins/magicLink/magicLink.controller.test.ts, src/services/auth/plugins/magicLink/magicLink.controller.ts, src/services/auth/plugins/magicLink/magicLink.schemas.ts, src/services/auth/plugins/password/password.controller.test.ts, src/services/auth/plugins/password/password.controller.ts, src/services/auth/plugins/password/password.schemas.ts
On password login, the `/auth` redirection link was returned as a string so the frontend could redirect manually.
Instead, we directly sign in the user in the `/login-password`. The redirection to some interface will happen in the frontend.
=> feat(password): set login session in password login

package.json, src/drizzle/0008_page.sql, src/drizzle/0009_page.sql, src/drizzle/meta/0008_snapshot.json, src/drizzle/meta/0009_snapshot.json, src/drizzle/meta/_journal.json, src/drizzle/schema.ts, src/drizzle/types.ts, src/services/item/discrimination.ts, src/services/item/index.ts, src/services/item/plugins/page/page.controller.test.ts, src/services/item/plugins/page/page.controller.ts, src/services/item/plugins/page/page.repository.ts, src/services/item/plugins/page/page.schemas.ts, src/services/item/plugins/page/page.service.ts, yarn.lock
Add entity and creation endpoint for a page.
A page is an item (type = 'page'). It has a dedicated table `page` that contains it's content. For now content is a jsonb column, but it can change depending on the yjs implementation.
close #1946
=> feat: create page endpoint

src/services/member/member.controller.test.ts, src/services/member/member.controller.ts, src/services/member/member.schemas.ts
To navigate to the item the guest has access to, we need the item id. This was forgotten when we added the item login properties to the current.
=> fix: add item id in current guest itemloginSchema
